# File: .readthedocs.yaml

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  commands:
    - versioningit . > protfasta/_version.py


# Specify Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Explicitly set the Python version and requirements file
python:
  install:
    - requirements: docs/requirements.txt
