# File: .readthedocs.yaml

version: 2

# Specify Python version and dependencies
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

# Commands to execute after dependency installation
build:
  os: ubuntu-20.04	
  tools: 
    python: "3"	  
  commands:
    - versioningit write > protfasta/_version.py  # Generate _version.py after dependencies are installed

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
