# File: .readthedocs.yaml

version: 2

# Specify Python version and dependencies
python:
  version: "3.9"
  install:
    - requirements: docs/requirements.txt

# Commands to execute after dependency installation
build:
  commands:
    - versioningit write > protfasta/_version.py  # Generate _version.py after dependencies are installed

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
