name: Run tox tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    name: Tox test on ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - toxenv: py310
            python-version: "3.10"
          - toxenv: py311
            python-version: "3.11"
          - toxenv: py312
            python-version: "3.12"
          - toxenv: py313
            python-version: "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: pip install tox

      - name: Run tox
        run: tox -e ${{ matrix.toxenv }}