name: Run tox tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    name: Tox test on ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: ["py310", "py311", "py312"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.toxenv[2:5] }}

      - name: Install tox
        run: pip install tox

      - name: Run tox
        run: tox -e ${{ matrix.toxenv }}